#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  render-k8s-api-values.sh --cluster CLUSTER_NAME --output OUTPUT_FILE

Example:
  render-k8s-api-values.sh \
    --cluster adc-k02 \
    --output k8s_kind/k02/cilium/runtime/10-k8s-api.yaml
EOF
}

cluster_name=""
output_file=""

while (( $# > 0 )); do
  case "$1" in
    --cluster)
      cluster_name="${2:-}"
      shift 2
      ;;
    --output)
      output_file="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "${cluster_name}" || -z "${output_file}" ]]; then
  usage >&2
  exit 2
fi

readonly control_plane="${cluster_name}-control-plane"

if ! docker inspect "${control_plane}" >/dev/null 2>&1; then
  echo "control-plane container not found: ${control_plane}" >&2
  exit 1
fi

api_host="$({
  docker exec "${control_plane}" \
    ip -4 -o address show dev eth0 scope global
} | awk 'NR == 1 { split($4, address, "/"); print address[1] }')"

if [[ ! "${api_host}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
  echo "failed to discover the control-plane eth0 IPv4 address" >&2
  exit 1
fi

mapfile -t cluster_nodes < <(
  docker ps --filter "name=^/${cluster_name}-(control-plane|worker[0-9]*)$" \
    --format '{{.Names}}' | sort
)

if (( ${#cluster_nodes[@]} == 0 )); then
  echo "no running nodes found for cluster: ${cluster_name}" >&2
  exit 1
fi

for node in "${cluster_nodes[@]}"; do
  response="$(
    docker exec "${node}" \
      curl --noproxy '*' --connect-timeout 3 --max-time 5 \
        --fail --silent --show-error --insecure \
        "https://${api_host}:6443/livez"
  )"
  if [[ "${response}" != "ok" ]]; then
    echo "API /livez check failed from ${node}: ${response}" >&2
    exit 1
  fi
done

output_dir="$(dirname "${output_file}")"
mkdir -p "${output_dir}"
tmp_file="$(mktemp "${output_dir}/.k8s-api-values.XXXXXX")"
trap 'rm -f "${tmp_file}"' EXIT

printf '%s\n' \
  '# Generated by render-k8s-api-values.sh. Do not commit this file.' \
  "k8sServiceHost: \"${api_host}\"" \
  'k8sServicePort: "6443"' > "${tmp_file}"

install -m 0644 "${tmp_file}" "${output_file}"
echo "rendered ${output_file} with API endpoint ${api_host}:6443"
