apiVersion: v1
kind: Service
metadata:
  name: demo-lb
  namespace: default
spec:
  type: LoadBalancer

  # ★ dual-stack 指定
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6

  selector:
    app: demo
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: web
          image: nginx:stable
          ports:
            - containerPort: 80